### ISSUE TITLE
Document installation for github organizations

### ISSUE THREAD

**Issue by Aariq** [fairdataihub/codefair-app#109]
I tried installing the app, but it couldn't see any of my repos inside of GitHub organizations.  I'm not sure if there's a way to get around this, or if I have to ask the organization owner to install the app.  Would be nice if there was something in the README about this.

**Comment by slugb0t** [comment]
This issue might be due to you not having certain permissions on the organization you are trying to install on. You will either need admin-level permissions or be the owner of the organization. Please refer to [here](https://docs.github.com/en/apps/using-github-apps/installing-a-github-app-from-github-marketplace-for-your-organizations#requirements-to-install-a-github-app-on-an-organization).

Another possibility could be the organization may have settings in place that restrict who can install github apps.

We'll make a note on this and add this information to our documentation, thank you.

**Comment by Aariq** [comment]
I could see the repo when I installed directly from the public page, which is now correctly linked on GitHub

**Comment by slugb0t** [comment]
Interesting, so you don't see the repo when installing from the marketplace link or was the issue just the link not being up to date?

**Comment by Aariq** [comment]
When I install from https://github.com/apps/codefair-io the first screen I see is:
<img width="554" alt="Screenshot 2024-11-27 at 3 50 28 PM" src="https://github.com/user-attachments/assets/eb2b16bf-f888-487b-9ddf-84301ca7e220">
All the organizations I belong to are listed.

When I installed from the marketplace I saw something more like this as the first step:

<img width="549" alt="Screenshot 2024-11-27 at 3 53 02 PM" src="https://github.com/user-attachments/assets/254d0056-dfb3-4bb3-9e33-7e3562fcfdea">

I can't seem to re-create this though—even though I've uninstalled the app, I can't seem to re-install it from the GitHub marketplace 🤷‍♂️

**Comment by Aariq** [comment]
I guess the difference is that with the marketplace, I didn't have a choice of which organization to install the app in

**Comment by slugb0t** [comment]
Ahh I see, from looking at the Marketplace listing. On the pricing and setup section that's where you will select the organization or personal account to install from.
![image](https://github.com/user-attachments/assets/8f4964d7-a97a-4bc4-8af3-b04645994ee4)

**Comment by Aariq** [comment]
Ah, I see.  I don't have that drop-down because I've already installed it on all of my GitHub accounts
