### ISSUE TITLE
CITATION.cff not recognized?

### ISSUE THREAD

**Issue by Aariq** [fairdataihub/codefair-app#111]
I have a repo with a CITATION.cff but no codemeta.yml and the metadata check failed (https://github.com/cct-datascience/github-actions-for-research/issues/3).  I was surprised that when I clicked the button to "Add Metadata" the metadata wasn't populated from the CITATION.cff I already have.  It would be nice if this tool could "translate" between CITATION.cff and codemeta.yml to help generate one when the the other is missing.

**Comment by slugb0t** [comment]
Currently, Codefair retrieves metadata primarily from GitHub's API and an existing codemeta.json file, which is why the metadata check fails if either is missing. However, we’re excited to share that this issue will be addressed in our upcoming update (version 3.2.0).

With this update, the app will gather metadata from multiple sources, including citation.cff files, codemeta.json files, and GitHub's API.

Also please note that Codefair supports codemeta.json files but not codemeta.yml files, which might also impact the FAIR checks depending on your repository setup.

**Comment by slugb0t** [comment]
@Aariq excited to share that Codefair version 3.2.0 has been released! 🎉

This update specifically addresses the citation.cff issue we discussed earlier. With version 3.2.0, Codefair now supports gathering metadata from multiple sources, including:

    citation.cff files
    codemeta.json files
    GitHub's API

**Comment by Aariq** [comment]
Sweet!  I'll try it out again on my next project
